version: '3.7'
services:
  book-store:
    build:
      context: .
      target: production
    ports:
      - '3000:3000'
    environment:
      # DATABASE
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_USERNAME: $DATABASE_USERNAME
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE: $DATABASE
      # AUTH
      JWKS_URL: $JWKS_URL
    depends_on:
      - database

  database:
    image: mysql:8.0.32
    environment:
      MYSQL_DATABASE: $DATABASE
      MYSQL_USER: $DATABASE_USERNAME
      MYSQL_PASSWORD: $DATABASE_PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql

volumes:
  database: